name: surrealdb_js
description: Flutter SurrealDB SDK for JavaScript
version: 0.1.0+1


environment:
  sdk: "^3.4.0"
  flutter: "^3.22.0"

dependencies:
  flutter:
    sdk: flutter
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - assets/js/