name: surrealdb_js
description: Flutter SurrealDB SDK for JavaScript
version: 1.0.0-beta.14
repository: https://github.com/limcheekin/surrealdb_js

environment:
  sdk: "^3.4.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ">=5.1.0 <7.0.0"

flutter:
  assets:
    - assets/js/