name: Build surrealdb.js files
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout own repo
        uses: actions/checkout@v4

      - name: Checkout surrealdb.js repo (latest tag)
        run: |
          git clone https://github.com/surrealdb/surrealdb.js.git
          cd surrealdb.js;export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          git checkout $LATEST_TAG

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: |
          cd surrealdb.js
          bun install
          bun run build

      - name: "Copy build files to the assets/js directory"
        run: cp -u surrealdb.js/dist/index.bundled.mjs assets/js/

      - name: "Git commit surrealdb_js assets"
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@users.noreply.github.com"
          git add assets/js/index.*
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "chore: updated assets/js"
            git push
          fi
